name = "MusicManipulations"
uuid = "0696f8b0-8469-11e8-2dd1-81a184564249"
authors = ["George Datseris <datseris.george@gmail.com>", "Lennart Jahn <l.jahn@stud.uni-goettingen.de>"]
repo = "https://github.com/JuliaMusic/MusicManipulations.jl.git"
version = "0.1.0"

[deps]
MIDI = "f57c4921-e30c-5f49-b073-3f2f2ada663e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
